name: Expression
run-name: Practicando con expresiones
on:
  workflow_dispatch:
    inputs:
      edad:
        description: 'Edad'
        required: true
        type: number
        default: 18
      nombre:
        description: 'Nombre'
        required: true
        default: 'Marco'
        type: string
jobs:
  mayor:
    if: ${{ inputs.edad >= 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es mayor de edad
  menor:
    if: ${{ inputs.edad < 18 }}
    runs-on: ubuntu-latest
    steps:
      - name: Correr script
        run: echo ${{ inputs.nombre }} es menor de edad